---
{{- if not .Values.credentials.existingTargetRegistrySecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-image-mirror.fullname" . }}-target-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-image-mirror.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.credentials.targetRegistryUsernameKey }}: {{ .Values.credentials.targetRegistryUsername | quote }}
  {{ .Values.credentials.targetRegistryPasswordKey }}: {{ .Values.credentials.targetRegistryPassword | quote }}
{{- end }}
---
{{- if not .Values.credentials.existingSourceRegistrySecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-image-mirror.fullname" . }}-source-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-image-mirror.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.credentials.sourceRegistryUsernameKey }}: {{ .Values.credentials.sourceRegistryUsername | quote }}
  {{ .Values.credentials.sourceRegistryPasswordKey }}: {{ .Values.credentials.sourceRegistryPassword | quote }}
{{- end }}
