name: Chart PR

on:
  pull_request:
    paths:
      - 'chart/templates/**'
      - 'chart/tests/**'
      - 'chart/values**'

jobs:
  helm:
    name: Helm chart test
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v6

      - uses: azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310 # v5.0.1
        id: install-helm
        with:
          version: 'v3.20.2'

      - name: Install Helm plugins
        shell: bash
        run: |
          make plugins

      - name: Test Helm Chart
        shell: bash
        run: |
          make helm-test
