name: Chart PR

on:
  pull_request:
    paths:
      - 'chart/templates/**'
      - 'chart/tests/**'
      - 'chart/values**'

jobs:
  helm:
    name: Helm chart test
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v6

      - uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # v5.0.0
        id: install-helm
        with:
          version: 'v4.2.4'

      - name: Install Helm plugins
        shell: bash
        run: |
          make plugins

      - name: Test Helm Chart
        shell: bash
        run: |
          make helm-test
