name: Trigger Release

on:
  push:
    branches:
      - main
    paths:
      - 'chart/**'
      - 'docker/**'

jobs:
  trigger-release:
    name: Trigger Release
    runs-on: ubuntu-latest
    steps:
      - name: Create release PR
        id: release
        uses: googleapis/release-please-action@5c625bfb5d1ff62eadeeb3772007f7f66fdcf071 # v4.4.1
        with:
          token: ${{ secrets.RELEASE_GITHUB_PAT }}
          release-type: helm
