name: Trigger Release

on:
  push:
    branches:
      - main
    paths:
      - 'docker/**'
      - 'chart/templates/**'
      - 'chart/tests/**'
      - 'chart/values**'

jobs:
  trigger-release:
    name: Trigger Release
    runs-on: ubuntu-latest
    steps:
      - name: Create release PR
        id: release
        uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5
        with:
          token: ${{ secrets.RELEASE_GITHUB_PAT }}
